### ISSUE TITLE
How to create a link to launch gdlde from desktop in ubuntu? 

### ISSUE THREAD

**Issue by wogallery** [gnudatalanguage/gdlde#11]
I have successfully built and installed gdlde in Ubuntu linux. I can launch gdlde from a terminal using the command:

/usr/src/gdlde/product/target/products/gdlde.product/linux/gtk/x86_64/gdlde

However, this is awkward. How do I create a link to this executable in a more accessible place?

I have tried:
ln -s /usr/src/gdlde/product/target/products/gdlde.product/linux/gtk/x86_64/gdlde /home/william/Desktop/gdlde
But double clicking this link opens gdlde in Emacs. If I select properties>Open With for this link, the default application is Emacs. I tried changing the default application to Run Software but when I double click, nothing happens.

Suggestions appreciated.
Bil

**Comment by slayoo** [comment]
@olebole - any hints?

**Comment by olebole** [comment]
Ahh, to have an answer here: you need to create a `gdlde.desktop` file. Here is an example from DS9:
```config
[Desktop Entry]
Version=1.0
Name=SAOImage DS9 
GenericName=Image Viewer
Comment=Astronomical Data Visualization Application
Type=Application
Exec=ds9 %F
Icon=SAOImageDS9.svg
StartupWMClass=Ds9.tcl
Categories=Education;Science;Astronomy;
Keywords=FITS;Astronomy;Viewer;
```

**Comment by slayoo** [comment]
Thank @olebole!
@pjb7687 any hints where to put this file and how to instruct any installation procedure to put it in the right place?
