### ISSUE TITLE
Problem starting gdlde on mac

### ISSUE THREAD

**Issue by namned** [gnudatalanguage/gdlde#13]
I downloaded the zip file for gdlde v1.0.0 for a macbook running macOS 11.6. When I unzip it I get a 'button' labelled 'Eclipse'. When I click it I get a window that says: [“Eclipse” is damaged and can’t be opened. You should move it to the Trash.]. I have repeated this several times, always with the same result. Even tried the versions several days earlier.
<img width="264" alt="Screen Shot 2021-11-24 at 17 36 43" src="https://user-images.githubusercontent.com/95004296/143349159-05a9676a-cabc-4cb1-97f9-e68739df6ac2<img width="264" alt="Screen Shot 2021-11-24 at 17 36 43" src="https://user-images.githubusercontent.com/95004296/143350423-22837d03-df76-4cf9-85fb-89124c5c2132.png">png">

**Comment by pjb7687** [comment]
Hi @namned, may I ask you are using an Intel mac?

**Comment by namned** [comment]
Hi Jeongbin,

Yes the processor is a 2.3 GHz 8-Core Intel Core i9

Thanks, Ken Denman

**Comment by namned** [comment]
Namned here again. I have tried to follow the instructions in the README.md file for gdlde, but am a bit lost, as I do not work in Linux. 
First I have installed 'jdk-17.0.1.jdk' in /Library/Java, but I don't know what is meant by 'the top source directory'. When I try to install it in /Users/myname or in /idlde I get the message 'zsh: no such file or directory: ./mvnw'. So I don't know what to do next.

**Comment by namned** [comment]
I did not mean to close this issue, just after I had elaborated on my inability to make gdlde. But I do need some help and guidance. namned

**Comment by pjb7687** [comment]
Hi @namned, I think maybe you can also try out this method: https://merikan.com/2013/08/eclipse-is-damaged-and-cant-be-opened/

**Comment by namned** [comment]
Hi,
I followed those instructions and managed to get rid of that message. It turns out that I had not installed Java JDK correctly, but with help from a YouTube video. Still need to figure out how to set up the pointer for gdlde to find GDL.

Thanks, @namned

**Comment by namned** [comment]
HI Back again. I am on a mac with intel processor running macOS Monterey. I can open 'gdlde', but no matter what i try I alway get the message that I need to set the environmental variable GDL_HOME. I set it to the home directory of gdl but the message does not change. I attach 4 screen grabs: 1. the window when GDLDE opens, 2. the shell program that sets GDL_HOME before it opens gdlde, 3. the session output from 'Terminal' on the macbook, I check the environmental variables 'printenv' before and after starting gdlde, and 4. the directory structure for Users/denmank.  I hope you can help me, I am a novice at LINUX.  THank
<img width="693" alt="GDLDE GU
<img width="582" alt="Terminal Session Ma
<img width="898" alt="Directory structure for :Users:denmank 27 Jan 22" src="https://user-images.githubusercontent.com/95004296/151450020-e4eab1f9-c3b4-4c25-838c-71445f5b38b8.png">
c 27 Jan 22" src="https://user-images.githubusercontent.com/95004296/151449997-a543da21-ebb8-4817-ba02-6bdd9a6dba02.png">
I screen 27 Ja
<img width="777" alt="Shell script 'run_gdlde sh' 27Jan 22 " src="https://user-images.githubusercontent.com/95004296/151449967-88bb48fb-17eb-43d3-864d-1d6ca3561d5a.png">
n 22" src="https://user-images.githubusercontent.com/95004296/151449940-91ba748c-17bf-4f3b-af73-711823c25d7b.png">
s

**Comment by pjb7687** [comment]
Hi @namned,

Thanks for the report, and actually I am aware of this, and fixing this doesn't seem to be trivial. This is because the MacOS seems to ignore the global environment settings while GUI apps start-up and use their own dedicated way to get the settings from the one similar to the registry thing of MS windows. I will have a closer look at this issue perhaps one or two months later, when I get a Mac machine on my hand.
