### ISSUE TITLE
gdlde uses wrong java version

### ISSUE THREAD

**Issue by gcomes** [gnudatalanguage/gdlde#14]
I'm on CentOS 8, I have openjdk 1.8.0 and 11 installed.
When I build gdlde with mvnw if I don't set JAVA_HOME the build fails because
java 1.8 is used, but if I set the appropriate JAVA_HOME then the build succeed.
However, when I start gdlde it fails and the log contains:
>   eclipse.buildId=unknown
>   java.version=1.8.0_312
>   java.vendor=Red Hat, Inc.
>   BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
>   Command-line arguments:  -os linux -ws gtk -arch x86_64

**Comment by pjb7687** [comment]
Hi, I think you can try changing your default java version:

```
$ sudo update-alternatives --config java
```

**Comment by gcomes** [comment]
Thank you for your answer. I know I have several way to make 
gdlde run without error (update-alternatives, uninstall java 1.8.0, etc).
But all of them requires a change to the system.
What if I do not have administrative privileges?
Shouldn't be possible to tell gdlde with version of java to use
(the one used to build it)?
