### ISSUE TITLE
Slight change of wording to your readme.md file would have saved me hours of "troubleshooting"

### ISSUE THREAD

**Issue by bisi-sysadmin** [gnudatalanguage/gdlde#15]
being a complete noob to GDL and GDLDE, but a vastly experience unix sysadmin, I missed the significance of your subtitle/description:
"An IDE for GDL (GNU Data Language), based on Eclipse RCP."

it would have been *much* clearer to this native english speaker if you had written:
"An IDE for GDL (GNU Data Language), requiring Eclipse IDE"

And maybe included a link to the eclipse.org installer page for eclipse IDE https://www.eclipse.org/downloads/packages/installer

The phrase "based on..." is generally used to mean "I borrowed a lot of ideas from, and want to give credit to...".  It is not generally used to mean that the thing referred to is a pre-requisite.

But thanks for a great project!  The fellow I am helping (who needs GDL because he has lost his access to IDL after retiring) is over the moon that it all works for him.

**Comment by slayoo** [comment]
Thank you!
Changed: https://github.com/gnudatalanguage/gdlde/commit/341462a9f3c9d0acdcd7816406531e711239d54b

**Comment by pjb7687** [comment]
Sorry, but I think I don't get your point. GDLDE (or GDL Workbench) is really "based on" Eclipse RCP, which refers to the Rich Client Platform of the Eclipse project. Eclipse IDE is NOT a prerequisite, GDLDE is completely standalone software.

The only prerequisite is rather a Java JVM, which I didn't bundle, to simply reduce the size of the releases.

**Comment by pjb7687** [comment]
I reverted the commit.

**Comment by slayoo** [comment]
Thanks, @pjb7687, and sorry

**Comment by pjb7687** [comment]
> Thanks, @pjb7687, and sorry

No problem!

**Comment by pjb7687** [comment]
To prevent further confusion, I added a link to RCP in README. Hope it helps noobs who are not familiar with the jargons.
