### ISSUE TITLE
Plot window does not open with gdlde

### ISSUE THREAD

**Issue by Csega** [gnudatalanguage/gdlde#16]
Hi All!

When I try to plot something in the gdlde command prompt, be it just something as simple as:

```idl
plot,findgen(100)
```

the windows does not appear. I tried it on the native windows release of gdl+gdlde. This case the plot window opens behind the gdlde main window (but under the same taskbar icon). The second plot command puts it before the main window, but still using the same taskbar icon.

When I try the same in WSL2 (running Ubuntu 22.04 LTS on a Windows 11 host) using GitHub main repository and compile both gdl and gdlde, then nothing is displayed, but when I write another command in (like a=findgen(100)), the window is displayed (again, under the same icon as on the native windows version), but I cannot move the window anywhere, only close it.

Can you help me figure out, what to do to be the plot windows correctly displayed?

Cheers,
Csega

**Comment by Csega** [comment]
I found these two links regarding this topic, I don't know, if it helps or not.

1. [Eclipse RPC Java create new window](https://stackoverflow.com/questions/46269385/eclipse-rcp-java-create-new-window)
2. [Create new workbench window](https://www.eclipse.org/forums/index.php/t/1057782/)

**Comment by pjb7687** [comment]
Hi @Csega, Thanks! May I ask what version of GDL you have tried? I've also checked the links you provided, but actually, the plot windows are managed by GDL's wxwidgets but not Eclipse, so I think they are unrelated.

**Comment by Csega** [comment]
Hi @pjb7687! On Windows I have some weekly release (standard version), but I could not find, which one exactly. On Linux I use the git main for both gdl and gdlde. Both of them are more than a few days old.

But now I tried the 1.0.1 release on Windows (also the standard version) and it works as expected! So it seems, that something happened since the 1.0.1 release. On the gdl wxwidgets parts, it seems.

**Comment by pjb7687** [comment]
Could you try plotting something with command-line GDL without gdlde?

**Comment by Csega** [comment]
@pjb7687 I tried that as well and that works without any problems.

**Comment by pjb7687** [comment]
That's interesting, I will have a look later. But at the moment I am super busy, and I think I'm going to have some time later next month.

**Comment by Csega** [comment]
Hi @pjb7687,

is there any news on this? Did you have the time to look into the issue? I just noticed, that it was marked as stale, that's why I thought I would ask to keep it alive.

Cheers!
Csega

**Comment by pjb7687** [comment]
Sorry the last semester ended in December and I have just had 2 consecutive conferences and I will be back to work next week. I will have a look then.. Thanks for the reminder!

**Comment by alaingdl** [comment]
I have a request from a colleague working on MSwin concerning such a tool. What is the status of `gdlde` ? thanks

**Comment by pjb7687** [comment]
@alaingdl Although no updates for a while, it is still working. It is currently bundled with the Windows installer.
