### ISSUE TITLE
Build errors  GDLDE in windows10 X_64 using Gradle 6.9 and openjdk 11

### ISSUE THREAD

**Issue by youngastronomy** [gnudatalanguage/gdlde#17]
While Build the GDLDE in windows10 X_64 using Gradle 6.9 and openjdk 11 showing those errors:

[INFO] --- tycho-p2-publisher-plugin:2.1.0:publish-products (default-publish-products) @ gdlde.product ---
[ERROR] Cannot resolve dependencies of product gdlde.product:
[ERROR]   eclipse-plugin artifact with ID "org.eclipse.m2e.maven.indexer" and version matching "0.0.0" was not found in the target platform
[ERROR]   eclipse-plugin artifact with ID "org.eclipse.m2e.maven.runtime.slf4j.simple" and version matching "0.0.0" was not found in the target platform
[ERROR]   eclipse-plugin artifact with ID "org.eclipse.swt.browser.chromium.win32.win32.x86_64" and version matching "0.0.0" was not found in the target platform

What happend here? How to fixed it?

**Comment by youngastronomy** [comment]
Problem is caused by the latest eclipse package are lack of those three items. Changed the the corresponding items to   <eclipse-repo.url>https://download.eclipse.org/releases/2020-12/</eclipse-repo.url> in the file pom.xml. Problem solved

**Comment by pjb7687** [comment]
Hi @youngastronomy, May I ask if you could make a commit? Then I will merge it to the tree.
