### ISSUE TITLE
GDL IDE not starting

### ISSUE THREAD

**Issue by alexwf1** [gnudatalanguage/gdlde#23]
Hi! I'm trying to setup the GDL IDE because I need it for class and we have a limited number of IDL licenses. The command line runs fine, but the IDE won't open and generates an error log ([1726656385265.log](https://github.com/user-attachments/files/17042784/1726656385265.log)). I'm on Windows 10, version 10.0.19045. 

I've installed JDK 23 as per the readme instructions, but there's a step I don't understand: "With the JDK version equal or higher than 11 installed, type the following at the top source directory". Sorry if it's a stupid question, but I don't really know what this means or whether it's necessary for the installation. 

Thank you in advance for any help you can give me. I'm not a compsci student, so most of this stuff really goes over my head.

**Comment by pjb7687** [comment]
Hi @alexwf1, That direction is to compile GDLDE which only is the case when you want to build GDLDE from the source code. As you just want to install and run it, it is not needed.

I had a look at your log file, it seems GDLDE picks up the wrong JRE installed on your machine (java 8). The easiest thing you can do is to remove Java 8 and try reinstalling Java 11 (or higher). If it is not allowed, you should set a different JAVA_HOME, I guess.

**Comment by alexwf1** [comment]
@pjb7687 thank you so much!! I thought I had already uninstalled the previous version, but apparently it was still there. GDLDE is launching fine now!
