### ISSUE TITLE
Enhancement request: Integrate with the Linux distribution repositories

### ISSUE THREAD

**Issue by texadactyl** [gnudatalanguage/gdlde#3]
For example, I can install gdl and astro-gdl from the Ubuntu and Debian repositories.  I would like to be able to do the same with gdlde.

**Comment by slayoo** [comment]
good point, thanks!
yet first, we need to sort out current problems with running gdlde with current Java versions (#2).

**Comment by slayoo** [comment]
@gnudatalanguage/gdlpackagers any thoughts?
Thanks to recent updates from @pjb7687, gdlde has apparently attracted more interest and indeed it would be great to offer it to GDL package users!

**Comment by opoplawski** [comment]
Speaking for Fedora - it ain't going to happen anytime soon.  Fedora requires everything to be built from source and the Java/Eclipse stack collapsed a while back due to lack of maintainers.  So the required dependencies with which to build gdlde are no longer in the Fedora repository.  Sorry. :(
